theme = "meliora"

[editor]
# Minimum severity to show a diagnostic after the end of a line:
end-of-line-diagnostics = "hint"
bufferline = "always"
gutters = ["diagnostics", "spacer", "line-numbers", "spacer"]
scrolloff = 999
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-base-name", "file-modification-indicator", "read-only-indicator"]
right = ["file-type", "diagnostics", "workspace-diagnostics", "separator", "selections", "primary-selection-length", "separator", "total-line-numbers", "position"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "error"
# Minimum severity to show a diagnostic on other lines:
[editor.file-picker]
hidden = false
